services:
  litellm:
    image: 'ghcr.io/berriai/litellm:{{ LITELLM_TAG }}'
    command: ['--config', '/app/config.yaml', '--detailed_debug']
    environment:
      - 'TZ=Asia/Singapore'
      - 'LITELLM_MASTER_KEY={{ LITELLM_MASTER_KEY }}'
      - 'LITELLM_SALT_KEY={{ LITELLM_SALT_KEY }}'
      - 'DATABASE_URL=postgresql://{{ LITELLM_DB_USERNAME }}:{{ LITELLM_DB_PASSWORD }}@{{ LITELLM_DB_HOST }}:{{ LITELLM_DB_PORT }}/{{ LITELLM_DB_DATABASE }}'
      - 'PROXY_BASE_URL={{ urls.load_nginx_url(container, "web") }}'
#     {% if NGINX_AUTH_ENABLE %}
#     {% with client = manager.containers['authelia'].oidc_client %}
      - 'GENERIC_CLIENT_ID={{ client["client_id"] }}'
      - 'GENERIC_CLIENT_SECRET={{ client["client_secret"] }}'
      - 'GENERIC_AUTHORIZATION_ENDPOINT={{ client["issuer_url"] }}/api/oidc/authorization'
      - 'GENERIC_TOKEN_ENDPOINT={{ client["issuer_url"] }}/api/oidc/token'
      - 'GENERIC_USERINFO_ENDPOINT={{ client["issuer_url"] }}/api/oidc/userinfo'
#     {% endwith %}
#     {% endif %}
#   {% if LITELLM_PORT > 0 %}
    ports:
      - '{{ LITELLM_PORT }}:4000'
#   {% endif %}
    volumes:
      - '{{ (APP_PATH/"data") | mkdir | chown }}:/data'
      - '{{ SOURCE_PATH/"config.yaml" }}:/app/config.yaml:ro'
    networks:
      - nginx
      - litellm
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/health/liveliness']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
#   {% if LITELLM_DB_HOST == 'litellm-postgres' %}
    depends_on:
      - litellm-postgres
#   {% endif %}

# {% if LITELLM_DB_HOST == 'litellm-postgres' %}
  litellm-postgres:
    image: postgres:16-alpine
    volumes:
      - '{{ (APP_PATH/"postgres") | mkdir | chown }}:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: '{{ LITELLM_DB_DATABASE }}'
      POSTGRES_USER: '{{ LITELLM_DB_USERNAME }}'
      POSTGRES_PASSWORD: '{{ LITELLM_DB_PASSWORD }}'
    networks:
      - litellm
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U {{ LITELLM_DB_USERNAME }} -d {{ LITELLM_DB_DATABASE }}']
      interval: 10s
      timeout: 5s
      retries: 5
#   {% endif %}

networks:
  nginx:
  litellm:
