services:
  code-server:
    platform: linux/amd64
    user: '{{ DOCKER_UID }}:{{ DOCKER_GID }}'
    environment:
      - 'TZ=Asia/Singapore'
      - 'PASSWORD={{ VSCODE_PASSWORD }}'
#     {% if container.proxy_url %}
      - 'VSCODE_PROXY_URI={{ container.proxy_url }}'
#     {% endif %}
    cap_add:
      - SYS_ADMIN
#   {% if VSCODE_PORT > 0 %}
    ports:
      - '{{ VSCODE_PORT }}:8080'
#   {% endif %}
    volumes:
      - '{{ (APP_PATH/"home") | mkdir | chown(docker_user) }}:/workspace'
#     {% for name, path in containers["ai"].home_files.items() %}
      - '{{ path }}:/workspace/{{ name }}'
#     {% endfor %}
#     {% for name, path in containers["coder"].home_files.items() %}
      - '{{ path }}:/workspace/{{ name }}'
#     {% endfor %}
#     {% for name, path in containers["coder"].project_files.items() %}
      - '{{ path }}:/workspace/projects/{{ name }}'
#     {% endfor %}
#   {% if NGINX_AUTH_ENABLE %}
    command: ["--auth", "none"]
#   {% endif %}
    networks:
      - nginx

networks:
  nginx:
