services:
  aionui:
    user: '{{ DOCKER_UID }}:{{ DOCKER_GID }}'
    environment:
      - 'TZ=Asia/Singapore'
      - 'NODE_ENV=production'
      - 'AIONUI_ALLOW_REMOTE=true'
      - 'AIONUI_DATA_DIR=/workspace'
      - 'JWT_SECRET={{ AIONUI_JWT_SECRET }}'
#   {% if AIONUI_PORT > 0 %}
    ports:
      - '{{ AIONUI_PORT }}:{{ AIONUI_PORT }}'
#   {% endif %}
    volumes:
      - '{{ (APP_PATH/"home") | mkdir | chown }}:/workspace'
#     {% for name, path in containers["ai"].home_files.items() %}
      - '{{ path }}:/workspace/{{ name }}'
#     {% endfor %}
#     {% for name, path in containers["coder"].project_files.items() %}
      - '{{ path }}:/workspace/projects/{{ name }}'
#     {% endfor %}
    networks:
      - nginx

networks:
  nginx:
