services:
  ws-scrcpy:
    environment:
      - 'WS_SCRCPY_CONFIG=/ws-scrcpy/config.yaml'
    volumes:
      - '{{ manager.container_host }}:/var/run/docker.sock'
      - '{{ (APP_PATH/"config.yaml") | chown }}:/ws-scrcpy/config.yaml:ro'
    network_mode: host
    privileged: true
