services:
  cc-switch-web:
    image: 'ghcr.io/laliet/cc-switch-web:{{ CC_SWITCH_TAG }}'
    hostname: cc-switch-web
    environment:
      - 'ALLOW_HTTP_BASIC_OVER_HTTP=1'
      - 'HOME=/home/ccswitch'
    user: '{{ DOCKER_UID }}:{{ DOCKER_GID }}'
    volumes:
#     {% for name, path in containers["ai"].home_files.items() %}
      - '{{ path }}:/home/ccswitch/{{ name }}'
#     {% endfor %}
#   {% if CC_SWITCH_PORT > 0 %}
    ports:
      - '{{ CC_SWITCH_PORT }}:3000'
#   {% endif %}
    networks:
      - nginx

networks:
  nginx:
