services:
  qbittorrent:
    image: 'lscr.io/linuxserver/qbittorrent:{{ QBITTORRENT_TAG }}'
    environment:
      - 'PUID={{ DOCKER_UID }}'
      - 'PGID={{ DOCKER_GID }}'
      - 'TZ=Etc/UTC'
      - 'WEBUI_PORT=8080'
      - 'TORRENTING_PORT={{ QBITTORRENT_TORRENTING_PORT }}'
    volumes:
      - '{{ (APP_PATH/"config") | mkdir | chown(docker_user) }}:/config'
      - '{{ (DOCKER_DOWNLOAD_PATH/"qbittorrent") | mkdir | chown(docker_user) }}:/downloads'
#   {% if QBITTORRENT_PORT > 0 %}
    ports:
      - '{{ QBITTORRENT_PORT }}:8080'
      - '{{ QBITTORRENT_TORRENTING_PORT }}:{{ QBITTORRENT_TORRENTING_PORT }}'
      - '{{ QBITTORRENT_TORRENTING_PORT }}:{{ QBITTORRENT_TORRENTING_PORT }}/udp'
#   {% endif %}
    networks:
      - nginx

networks:
  nginx:
