services:
  hermes:
    image: nousresearch/hermes-agent:{{ HERMES_AGENT_TAG }}
    command: gateway run
#   {% if HERMES_AGENT_PORT > 0 %}
    ports:
      - '{{ HERMES_AGENT_PORT }}:8642'
#   {% endif %}
    volumes:
      - '{{ (APP_PATH/"data") | mkdir | chown }}:/opt/data'
    environment:
      - 'HERMES_UID={{ DOCKER_UID }}'
      - 'HERMES_GID={{ DOCKER_GID }}'
    networks:
      - hermes

  hermes-dashboard:
    image: nousresearch/hermes-agent:{{ HERMES_AGENT_TAG }}
    command: ["dashboard", "--host", "0.0.0.0", "--insecure", "--no-open"]
#   {% if HERMES_AGENT_DASHBOARD_PORT > 0 %}
    ports:
      - '{{ HERMES_AGENT_DASHBOARD_PORT }}:9119'
#   {% endif %}
    volumes:
      - '{{ (APP_PATH/"data") | mkdir | chown }}:/opt/data'
    environment:
      - 'HERMES_UID={{ DOCKER_UID }}'
      - 'HERMES_GID={{ DOCKER_GID }}'
    networks:
      - hermes
      - nginx
    depends_on:
      - hermes

networks:
  nginx:
  hermes:
