services:
  hermes:
    command: gateway run
    shm_size: '1g'
#   {% if HERMES_AGENT_PORT > 0 %}
    ports:
      - '{{ HERMES_AGENT_PORT }}:8642'
#   {% endif %}
    volumes:
      - '{{ (APP_PATH/"data") | mkdir | chown }}:/opt/data'
    networks:
      - hermes
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"

  hermes-dashboard:
    image: nousresearch/hermes-agent:{{ HERMES_AGENT_TAG }}
    command: dashboard --host 0.0.0.0 --insecure
#   {% if HERMES_AGENT_DASHBOARD_PORT > 0 %}
    ports:
      - '{{ HERMES_AGENT_DASHBOARD_PORT }}:9119'
#   {% endif %}
    volumes:
      - '{{ (APP_PATH/"data") | mkdir | chown }}:/opt/data'
    environment:
      - 'GATEWAY_HEALTH_URL=http://hermes:8642'
    networks:
      - hermes
      - nginx
    depends_on:
      - hermes
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

networks:
  nginx:
  hermes:
