location / {
    # include /etc/nginx/conf.d/snippets/header.conf;
    include /etc/nginx/conf.d/snippets/auth.conf;
    proxy_set_header Host "127.0.0.1:9119";
    proxy_set_header Origin "http://127.0.0.1:9119";
    proxy_pass http://hermes-dashboard:9120;
    include /etc/nginx/conf.d/snippets/params.conf;
}
