location ^~ /c/ {
    include /etc/nginx/conf.d/snippets/header.conf;
    set $target_url "http://sublink-pro:8000";
    proxy_pass $target_url;
}

location ~* \.(css|js|webmanifest)$ {
    include /etc/nginx/conf.d/snippets/header.conf;
    set $target_url "http://sublink-pro:8000";
    proxy_pass $target_url;
}

location / {
    include /etc/nginx/conf.d/snippets/header.conf;
    {% if AUTH_ENABLE %}
    include /etc/nginx/conf.d/snippets/auth.conf;
    {% if SUBLINK_API_KEY %}
    proxy_set_header X-API-Key "{{ SUBLINK_API_KEY }}";
    proxy_set_header Accept-Encoding "";
    sub_filter_once on;
    sub_filter '</head>' '<script>if(!localStorage.getItem("accessToken"))localStorage.setItem("accessToken","{{ manager.project_name }}");</script></head>';
    {% endif %}
    {% endif %}
    set $target_url "http://sublink-pro:8000";
    proxy_pass $target_url;
    include /etc/nginx/conf.d/snippets/params.conf;
}
