services:
  code-server:
    user: '{{ DOCKER_UID }}:{{ DOCKER_GID }}'
    environment:
      - 'TZ=Etc/UTC'
      - 'PASSWORD={{ VSCODE_PASSWORD }}'
#   {% if VSCODE_PORT > 0 %}
    ports:
      - '{{ VSCODE_PORT }}:8080'
#   {% endif %}
    volumes:
      - '{{ (APP_PATH/"home") | mkdir | chown(docker_user) }}:/workspace'
      - '{{ utils.join_path(CODER_LLM_PATH, ".codex") | mkdir | chown(docker_user) }}:/workspace/.codex'
      - '{{ utils.join_path(CODER_LLM_PATH, ".claude") | mkdir | chown(docker_user) }}:/workspace/.claude'
      - '{{ utils.join_path(CODER_LLM_PATH, ".cursor") | mkdir | chown(docker_user) }}:/workspace/.cursor'
      - '{{ utils.join_path(CODER_LLM_PATH, ".gemini") | mkdir | chown(docker_user) }}:/workspace/.gemini'
      - '{{ CODER_SSH_PATH | mkdir | chown(docker_user) }}:/workspace/.ssh'
      - '{{ CODER_PROJECT_PATH }}:/workspace/projects'
#   {% if NGINX_AUTH_ENABLE %}
    command: ["--auth", "none"]
#   {% endif %}
    networks:
      - nginx

networks:
  nginx:
