services:
  code-server:
    user: '{{ DOCKER_UID }}:{{ DOCKER_GID }}'
    environment:
      - 'TZ=Etc/UTC'
      - 'PASSWORD={{ VSCODE_PASSWORD }}'
#   {% if VSCODE_PORT > 0 %}
    ports:
      - '{{ VSCODE_PORT }}:8080'
#   {% endif %}
    volumes:
      - '{{ (APP_PATH/"home") | mkdir | chown(docker_user) }}:/workspace'
      - '{{ CODER_PROJECT_PATH }}:/workspace/projects'
      {% for name, path in containers["coder"].home_files.items() -%}
      - '{{ path }}:/workspace/{{ name }}'
      {% endfor %}
#   {% if NGINX_AUTH_ENABLE %}
    command: ["--auth", "none"]
#   {% endif %}
    networks:
      - nginx

networks:
  nginx:
