services:
  openwrt-builder:
    user: '{{ DOCKER_UID }}:{{ DOCKER_GID }}'
    volumes:
      - '{{ OPENWRT_BUILD_PATH | mkdir | chown(docker_user) }}:/data/openwrt'
      - '{{ (SOURCE_PATH/"configs") | chown(docker_user) }}:/data/configs'
      - '{{ (SOURCE_PATH/"patchs") | chown(docker_user) }}:/data/patchs'
#     {% for name, path in containers["coder"].home_files.items() %}
      - '{{ path }}:/workspace/{{ name }}'
#     {% endfor %}
    working_dir: "/data/openwrt"
    networks:
      - build

networks:
  build:
