services:
  cloudcli:
#   {% if CLOUD_CLI_PORT > 0 %}
    ports:
      - '{{ CLOUD_CLI_PORT }}:3001'
#   {% endif %}
    user: '{{ DOCKER_UID }}:{{ DOCKER_GID }}'
    volumes:
      - '{{ (APP_PATH/"home") | mkdir | chown(docker_user) }}:/workspace'
#     {% for name, path in containers["ai"].home_files.items() %}
      - '{{ path }}:/workspace/{{ name }}'
#     {% endfor %}
#     {% for name, path in containers["coder"].home_files.items() %}
      - '{{ path }}:/workspace/{{ name }}'
#     {% endfor %}
#     {% for name, path in containers["coder"].project_files.items() %}
      - '{{ path }}:/workspace/projects/{{ name }}'
#     {% endfor %}
    networks:
      nginx:

networks:
  nginx:
