services:
  redroid-builder:
    user: '{{ DOCKER_UID }}:{{ DOCKER_GID }}'
    volumes:
      - '{{ CODER_SSH_PATH | mkdir | chown(docker_user) }}:/workspace/.ssh'
      - '{{ REDROID_BUILD_PATH | mkdir | chown(docker_user) }}:/src'
      - '{{ (SOURCE_PATH/"scripts") | chown(docker_user) }}:/scripts:ro'
    environment:
      - 'LANG=en_US.UTF-8'
    working_dir: "/src"
    networks:
      - build

networks:
  build:
