services:
  redroid-builder:
    user: '{{ DOCKER_UID }}:{{ DOCKER_GID }}'
    volumes:
      - '{{ REDROID_BUILD_PATH | mkdir | chown(docker_user) }}:/src'
      - '{{ (SOURCE_PATH/"scripts") | chown(docker_user) }}:/scripts:ro'
#     {% for name, path in containers["coder"].home_files.items() %}
      - '{{ path }}:/workspace/{{ name }}'
#     {% endfor %}
    environment:
      - 'LANG=en_US.UTF-8'
    working_dir: "/src"
    networks:
      - build

networks:
  build:
